backend/config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    get '/search/users', to: "search#users", as: :search_users
    get '/search/products', to: "search#products", as: :search_products

    resources :dashboards, only: [] do
      collection do
        get :home
      end
    end

    resources :promotions do
      resources :promotion_rules
      resources :promotion_actions
      resources :promotion_codes, only: [:index]
    end

    resources :promotion_categories, except: [:show]

    resources :zones

    resources :countries do
      resources :states
    end
    resources :states
    resources :tax_categories

    resources :products do
      resources :product_properties do
        collection do
          post :update_positions
        end
      end
      resources :variant_property_rule_values, only: [:destroy] do
        collection do
          post :update_positions
        end
      end
      resources :images do
        collection do
          post :update_positions
        end
      end
      member do
        get :clone
      end
      resources :variants do
        collection do
          post :update_positions
        end
      end
      resources :variants_including_master, only: [:update]
      resources :prices, only: [:destroy, :index, :edit, :update, :new, :create]
    end
    get '/products/:product_slug/stock', to: "stock_items#index", as: :product_stock

    resources :option_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
    end

    delete '/option_values/:id', to: "option_values#destroy", as: :option_value

    resources :properties do
      collection do
        get :filtered
      end
    end

    delete '/product_properties/:id', to: "product_properties#destroy", as: :product_property

    resources :prototypes do
      member do
        get :select
      end

      collection do
        get :available
      end
    end

    resources :orders, except: [:show] do
      member do
        get :cart
        put :advance
        get :confirm
        put :complete
        post :resend
        get "/adjustments/unfinalize", to: "orders#unfinalize_adjustments"
        get "/adjustments/finalize", to: "orders#finalize_adjustments"
        put :approve
        put :cancel
        put :resume
      end

      resource :customer, controller: "orders/customer_details"
      resources :customer_returns, only: [:index, :new, :edit, :create, :update] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments, only: [:index, :new, :show, :create] do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [:new, :create, :edit, :update]
      end

      resources :reimbursements, only: [:index, :create, :show, :edit, :update] do
        member do
          post :perform
        end
      end

      resources :cancellations, only: [:index] do
        collection do
          post :short_ship
        end
      end
    end

    resource :general_settings, only: [:edit, :update] do
      collection do
        post :clear_cache
      end
    end

    resources :return_items, only: [:update]

    resources :taxonomies do
      collection do
        post :update_positions
      end
      resources :taxons
    end

    resources :taxons, only: [:index, :show] do
      collection do
        get :search
      end
    end

    resources :reports, only: [:index] do
      collection do
        get :sales_total
        post :sales_total
      end
    end

    resources :reimbursement_types, only: [:index]
    resources :adjustment_reasons, except: [:show, :destroy]
    resources :refund_reasons, except: [:show, :destroy]
    resources :return_reasons, except: [:show, :destroy]

    resources :shipping_methods
    resources :shipping_categories

    resources :stock_transfers, except: [:destroy] do
      member do
        get :receive
        put :finalize
        put :close
        get :tracking_info
        put :ship
      end
    end

    resources :stock_locations do
      resources :stock_movements, except: [:edit, :update, :destroy]
      collection do
        post :transfer_stock
        post :update_positions
      end
    end

    resources :stock_items, except: [:show, :new, :edit]
    resources :tax_rates

    resources :trackers
    resources :payment_methods do
      collection do
        post :update_positions
      end
    end

    resources :users do
      member do
        get :orders
        get :items
        get :addresses
        put :addresses
      end
      resources :store_credits, except: [:destroy] do
        member do
          get :edit_amount
          put :update_amount
          get :edit_validity
          put :invalidate
        end
      end
    end

    resources :style_guide, only: [:index]
  end

  get '/admin', to: 'admin/root#index', as: :admin
end

backend/app/controllers/spree/admin/product_properties_controller.rb
module Spree
  module Admin
    class ProductPropertiesController < ResourceController
      belongs_to 'spree/product', find_by: :slug
      before_action :find_properties
      before_action :setup_property, only: :index, if: -> { can?(:create, model_class) }
      before_action :setup_variant_property_rules, only: :index

      private

      def find_properties
        @properties = Spree::Property.pluck(:name)
      end

      def setup_property
        @product.product_properties.build
      end

      def setup_variant_property_rules
        @option_types = @product.variant_option_values_by_option_type
        @option_value_ids = (params[:ovi] || []).reject(&:blank?).map(&:to_i)
        @variant_property_rule = @product.find_variant_property_rule(@option_value_ids) || @product.variant_property_rules.build
        @variant_property_rule.values.build if can?(:create, Spree::VariantPropertyRuleValue)
      end
    end
  end
end

backend/app/views/spree/admin/product_properties/_product_property_fields.html.erb
<tr class="product_property fields" id="spree_<%= dom_id(f.object) %>" data-hook="product_property">
  <td class="no-border">
    <% if f.object.persisted? && can?(:update_positions, f.object) %>
      <span class="handle"></span>
      <%= f.hidden_field :id %>
    <% end %>
  </td>
  <td class='property_name'>
    <%= f.text_field :property_name, class: 'autocomplete' %>
  </td>
  <td class='value'>
    <%= f.text_field :value %>
  </td>
  <td class="actions">
    <% if f.object.persisted? && can?(:destroy, f.object) %>
      <%= link_to_delete f.object, no_text: true %>
    <% end %>
  </td>
</tr>

backend/app/views/spree/admin/product_properties/index.html.erb
<%= render 'spree/admin/shared/product_tabs', :current => 'Product Properties' %>
<%= render 'spree/shared/error_messages', :target => @product %>

<% content_for :page_actions do %>
  <% if can?(:create, Spree::ProductProperty) %>
    <ul class="tollbar inline-menu">
      <li>
        <%= link_to_add_fields Spree.t(:add_product_properties), 'tbody#product_properties', :class => 'plus button' %>
      </li>
      <li>
        <span id="new_ptype_link">
          <%= link_to Spree.t(:select_from_prototype), available_admin_prototypes_url, :remote => true, :class => 'button fa fa-copy' %>
        </span>
      </li>
    </ul>
  <% end %>
<% end %>

<%= form_for @product, :url => admin_product_url(@product), :method => :put do |f| %>
  <fieldset>
    <legend align="center"><%= plural_resource_name(Spree::ProductProperty) %></legend>
    <div class="add_product_properties" data-hook="add_product_properties"></div>

    <div id="prototypes" data-hook></div>

    <table class="index sortable" data-hook data-sortable-link="<%= update_positions_admin_product_product_properties_url %>">
      <thead>
        <tr data-hook="product_properties_header">
          <th colspan="2"><%= Spree::Property.model_name.human %></th>
          <th><%= Spree::ProductProperty.human_attribute_name(:value) %></th>
          <th class="actions"></th>
        </tr>
      </thead>
      <tbody id="product_properties" data-hook>
        <%= f.fields_for :product_properties do |pp_form| %>
          <%= render 'product_property_fields', :f => pp_form %>
        <% end %>
      </tbody>
    </table>

    <% if can?([:create, :update], Spree::ProductProperty) %>
      <%= render 'spree/admin/shared/edit_resource_links' %>
    <% end %>

    <%= hidden_field_tag 'clear_product_properties', 'true' %>
  </fieldset>
<% end %>

<%= form_tag admin_product_product_properties_path, method: :get, id: 'variant_option_value_selections' do %>
  <fieldset class='no-border-bottom'>
    <legend align="center"><%= Spree.t(:variant_properties) %></legend>
    <fieldset class='no-border-top'>
      <% @option_types.each do |option_type, option_values| %>
        <div class="field">
          <%= label :option_type_presentation, option_type.presentation %>
          <%= select_tag "ovi[]", options_from_collection_for_select(option_values, :id, :presentation, params[:ovi]), class: 'select2 fullwidth', include_blank: true, id: "#{option_type.name}_option_type_select" %>
        </div>
      <% end %>
      <div class="form-buttons filter-actions actions">
        <%= button Spree.t(:filter_results) %>
        <% if @option_value_ids.present? %>
          <%= link_to_add_fields Spree.t(:add_variant_properties), 'tbody#variant_property_values', class: 'plus button' %>
        <% end %>
      </div>
    </fieldset>
  </fieldset>
<% end %>

<%= form_for @product, url: admin_product_url(@product), method: :put do |f| %>
  <%= f.fields_for :variant_property_rules, @variant_property_rule do |rule_form| %>
    <%= rule_form.hidden_field 'id', value: @variant_property_rule.id %>
    <%= rule_form.hidden_field 'option_value_ids', value: @option_value_ids.join(',') %>
    <% if @option_value_ids.present? %>
      <fieldset class='no-border-top'>
        <table class="index sortable" data-hook data-sortable-link="<%= update_positions_admin_product_variant_property_rule_values_url %>">
          <thead>
            <tr data-hook="variant_property_values_header">
              <th colspan="2"><%= Spree::Property.model_name.human %></th>
              <th><%= Spree::ProductProperty.human_attribute_name(:value) %></th>
              <th class="actions"></th>
            </tr>
          </thead>
          <tbody id="variant_property_values" data-hook>
            <%= rule_form.fields_for :values do |values_form| %>
              <%= render 'product_property_fields', f: values_form %>
            <% end %>
          </tbody>
        </table>
        <% if can?([:create, :update], Spree::VariantPropertyRule) %>
          <%= render 'spree/admin/shared/edit_resource_links' %>
        <% end %>
      </fieldset>
    <% end %>
  <% end %>
<% end %>

<%= javascript_tag do -%>
  var properties = <%= raw(@properties.to_json) %>;
  $('#product_properties, #variant_property_values').on('keydown', 'input.autocomplete', function() {
    already_auto_completed = $(this).is('ac_input');
    if (!already_auto_completed) {
      $(this).autocomplete({source: properties});
      $(this).focus();
    }
  });
<% end -%>